//
//  PromptWordList.swift
//  Authorcise
//
//  Created by Colin Wright on 5/6/25.
//

import Foundation

struct Prompts {
    static let words: [String] = [
        "adventure", "mystery", "journey", "discovery", "secret", "magic", "wonder", "dream", "hope", "love",
        "friendship", "family", "home", "city", "forest", "mountain", "ocean", "river", "sky", "star",
        "moon", "sun", "light", "darkness", "shadow", "echo", "silence", "music", "song", "dance",
        "art", "story", "book", "poem", "letter", "message", "gift", "treasure", "key", "door",
        "window", "path", "road", "bridge", "gate", "wall", "garden", "flower", "tree", "animal",
        "bird", "fish", "insect", "dragon", "monster", "ghost", "spirit", "soul", "heart", "mind",
        "body", "voice", "touch", "smell", "taste", "sight", "sound", "feeling", "emotion", "thought",
        "idea", "memory", "future", "past", "present", "moment", "time", "eternity", "destiny", "fate",
        "chance", "luck", "fortune", "danger", "risk", "challenge", "quest", "mission", "purpose", "goal",
        "ambition", "success", "failure", "lesson", "wisdom", "knowledge", "truth", "lie", "illusion", "reality",
        "peace", "war", "conflict", "harmony", "balance", "chaos", "order", "freedom", "power", "courage",
        "fear", "strength", "weakness", "beauty", "grace", "charm", "smile", "laugh", "tear", "joy",
        "sorrow", "pain", "pleasure", "passion", "desire", "hunger", "thirst", "sleep", "awake", "alive",
        "dead", "birth", "death", "life", "cycle", "season", "spring", "summer", "autumn", "winter",
        "morning", "noon", "evening", "night", "dawn", "dusk", "twilight", "midnight", "yesterday", "today",
        "tomorrow", "always", "never", "often", "sometimes", "rarely", "usually", "again", "once", "twice",
        "first", "last", "next", "previous", "early", "late", "soon", "now", "then", "here",
        "there", "everywhere", "nowhere", "somewhere", "anywhere", "above", "below", "inside", "outside", "beside",
        "between", "among", "through", "across", "around", "beyond", "under", "over", "near", "far",
        "up", "down", "left", "right", "north", "south", "east", "west", "forward", "backward",
        "together", "alone", "apart", "open", "close", "start", "finish", "begin", "end", "continue",
        "stop", "pause", "play", "work", "rest", "create", "destroy", "build", "break", "fix",
        "heal", "hurt", "help", "hinder", "give", "take", "receive", "share", "keep", "lose",
        "find", "search", "hide", "reveal", "show", "tell", "ask", "answer", "listen", "speak",
        "watch", "see", "observe", "notice", "learn", "teach", "study", "read", "write", "draw",
        "paint", "sing", "act", "perform", "imagine", "believe", "trust", "doubt", "question", "wonder",
        "understand", "explain", "describe", "define", "compare", "contrast", "choose", "decide", "plan", "prepare",
        "try", "attempt", "succeed", "fail", "win", "lose", "fight", "defend", "attack", "protect",
        "save", "rescue", "escape", "survive", "explore", "travel", "visit", "return", "stay", "leave",
        "arrive", "depart", "meet", "greet", "welcome", "farewell", "remember", "forget", "forgive", "apologize",
        "thank", "praise", "criticize", "judge", "accept", "reject", "allow", "permit", "forbid", "prevent",
        "encourage", "discourage", "inspire", "motivate", "influence", "persuade", "convince", "promise", "swear", "vow",
        "hope", "wish", "pray", "dream", "imagine", "create", "invent", "design", "innovate", "discover",
        "explore", "investigate", "examine", "analyze", "solve", "resolve", "achieve", "accomplish", "complete", "fulfill",
        "celebrate", "mourn", "grieve", "rejoice", "suffer", "endure", "overcome", "conquer", "surrender", "yield",
        "grow", "change", "evolve", "transform", "develop", "improve", "progress", "decline", "fade", "disappear",
        "appear", "emerge", "materialize", "vanish", "exist", "become", "remain", "seem", "feel", "look",
        "sound", "taste", "smell", "touch", "sense", "perceive", "realize", "recognize", "comprehend", "grasp",
        "interpret", "translate", "communicate", "express", "convey", "relate", "connect", "disconnect", "unite", "separate",
        "join", "divide", "combine", "mix", "blend", "merge", "fuse", "melt", "freeze", "boil",
        "burn", "cool", "warm", "heat", "shine", "glow", "sparkle", "glitter", "flash", "beam",
        "radiate", "reflect", "absorb", "emit", "resonate", "vibrate", "tremble", "shake", "quiver", "flutter",
        "fly", "soar", "glide", "swim", "dive", "float", "sink", "crawl", "walk", "run",
        "jump", "leap", "climb", "descend", "ascend", "rise", "fall", "stand", "sit", "lie",
        "kneel", "bow", "stretch", "bend", "twist", "turn", "rotate", "spin", "whirl", "dance",
        "move", "still", "calm", "quiet", "loud", "noisy", "silent", "peaceful", "turbulent", "chaotic",
        "gentle", "rough", "smooth", "sharp", "blunt", "soft", "hard", "heavy", "light", "bright",
        "dim", "clear", "cloudy", "sunny", "rainy", "windy", "stormy", "snowy", "foggy", "icy",
        "hot", "cold", "warm", "cool", "dry", "wet", "humid", "arid", "fertile", "barren",
        "empty", "full", "hollow", "solid", "deep", "shallow", "wide", "narrow", "long", "short",
        "tall", "small", "large", "huge", "tiny", "giant", "dwarf", "young", "old", "new",
        "ancient", "modern", "future", "past", "eternal", "temporary", "permanent", "brief", "lasting", "fleeting",
        "swift", "slow", "quick", "gradual", "sudden", "instant", "constant", "variable", "random", "predictable",
        "certain", "uncertain", "possible", "impossible", "likely", "unlikely", "true", "false", "real", "fake",
        "genuine", "artificial", "natural", "synthetic", "simple", "complex", "easy", "difficult", "hard", "challenging",
        "beautiful", "ugly", "pretty", "plain", "elegant", "clumsy", "graceful", "awkward", "strong", "weak",
        "brave", "cowardly", "wise", "foolish", "smart", "stupid", "clever", "dull", "kind", "cruel",
        "generous", "selfish", "honest", "dishonest", "loyal", "disloyal", "faithful", "unfaithful", "happy", "sad",
        "joyful", "miserable", "angry", "calm", "excited", "bored", "surprised", "shocked", "amazed", "confused",
        "curious", "anxious", "worried", "nervous", "relaxed", "peaceful", "content", "satisfied", "dissatisfied", "grateful",
        "thankful", "proud", "humble", "ashamed", "guilty", "innocent", "responsible", "irresponsible", "patient", "impatient",
        "polite", "rude", "friendly", "hostile", "optimistic", "pessimistic", "serious", "playful", "funny", "boring",
        "interesting", "dull", "vivid", "pale", "colorful", "monochrome", "transparent", "opaque", "translucent", "shiny",
        "matte", "glossy", "rough", "smooth", "textured", "patterned", "plain", "striped", "dotted", "checkered",
        "abstract", "concrete", "symbolic", "literal", "figurative", "metaphorical", "allegorical", "mythical", "legendary", "historical",
        "fictional", "factual", "scientific", "philosophical", "spiritual", "religious", "secular", "sacred", "profane", "magical",
        "mystical", "ordinary", "extraordinary", "common", "rare", "unique", "special", "normal", "abnormal", "strange",
        "weird", "bizarre", "odd", "even", "perfect", "imperfect", "flawed", "flawless", "complete", "incomplete",
        "finished", "unfinished", "broken", "whole", "fragmented", "united", "divided", "connected", "isolated", "alone",
        "crowded", "empty", "spacious", "cramped", "open", "closed", "public", "private", "secret", "known",
        "unknown", "hidden", "visible", "obvious", "subtle", "mysterious", "enigmatic", "puzzling", "confusing", "clear",
        "ambiguous", "vague", "precise", "accurate", "inaccurate", "correct", "incorrect", "right", "wrong", "good",
        "bad", "evil", "virtuous", "wicked", "moral", "immoral", "ethical", "unethical", "just", "unjust",
        "fair", "unfair", "legal", "illegal", "lawful", "unlawful", "powerful", "powerless", "influential", "insignificant",
        "important", "trivial", "essential", "inessential", "necessary", "unnecessary", "vital", "critical", "crucial", "urgent",
        "pressing", "significant", "meaningful", "meaningless", "valuable", "worthless", "precious", "cheap", "expensive", "affordable",
        "rich", "poor", "wealthy", "destitute", "abundant", "scarce", "plentiful", "meager", "sufficient", "insufficient",
        "adequate", "inadequate", "healthy", "sick", "ill", "well", "fit", "unfit", "strong", "frail",
        "robust", "delicate", "alive", "lifeless", "energetic", "lethargic", "active", "passive", "dynamic", "static",
        "flexible", "rigid", "adaptable", "stubborn", "creative", "unimaginative", "original", "imitative", "innovative", "conventional",
        "traditional", "modern", "futuristic", "nostalgic", "optimistic", "hopeful", "despairing", "cynical", "idealistic", "realistic",
        "pragmatic", "romantic", "sentimental", "logical", "rational", "emotional", "intuitive", "instinctive", "conscious", "unconscious",
        "aware", "oblivious", "attentive", "distracted", "focused", "unfocused", "alert", "drowsy", "awake", "asleep",
        "dreaming", "lucid", "vivid", "hazy", "blurry", "sharp", "crisp", "defined", "undefined", "organized",
        "disorganized", "chaotic", "orderly", "systematic", "methodical", "random", "spontaneous", "planned", "intentional", "accidental",
        "voluntary", "involuntary", "compulsive", "obsessive", "addictive", "free", "bound", "liberated", "oppressed", "independent",
        "dependent", "autonomous", "subordinate", "superior", "inferior", "equal", "unequal", "similar", "different", "alike",
        "distinct", "unique", "identical", "opposite", "contrary", "parallel", "perpendicular", "convergent", "divergent", "concentric",
        "eccentric", "symmetrical", "asymmetrical", "balanced", "unbalanced", "stable", "unstable", "secure", "insecure", "safe",
        "dangerous", "protected", "vulnerable", "exposed", "shielded", "armored", "defenseless", "prepared", "unprepared", "ready",
        "unready", "willing", "unwilling", "eager", "reluctant", "enthusiastic", "apathetic", "motivated", "unmotivated", "inspired",
        "uninspired", "passionate", "dispassionate", "engaged", "detached", "involved", "uninvolved", "committed", "uncommitted", "devoted",
        "indifferent", "curious", "incurious", "adventurous", "cautious", "bold", "timid", "daring", "hesitant", "confident",
        "doubtful", "certain", "skeptical", "trusting", "gullible", "naive", "sophisticated", "worldly", "innocent", "corrupt",
        "pure", "tainted", "clean", "dirty", "spotless", "stained", "flawless", "blemished", "perfect", "damaged",
        "repaired", "restored", "renewed", "reborn", "reawakened", "transformed", "altered", "modified", "adjusted", "adapted",
        "refined", "purified", "simplified", "complicated", "elaborated", "condensed", "expanded", "contracted", "stretched", "compressed",
        "inflated", "deflated", "magnified", "minimized", "amplified", "reduced", "increased", "decreased", "multiplied", "divided",
        "added", "subtracted", "ascended", "descended", "accelerated", "decelerated", "started", "stopped", "paused", "resumed",
        "continued", "interrupted", "delayed", "postponed", "advanced", "retreated", "progressed", "regressed", "evolved", "devolved",
        "matured", "aged", "rejuvenated", "withered", "flourished", "decayed", "blossomed", "faded", "brightened", "dimmed",
        "clarified", "obscured", "revealed", "concealed", "exposed", "hidden", "discovered", "lost", "found", "misplaced",
        "recovered", "retrieved", "rescued", "abandoned", "saved", "destroyed", "preserved", "conserved", "protected", "neglected",
        "cherished", "despised", "loved", "hated", "adored", "detested", "admired", "scorned", "respected", "disrespected",
        "honored", "dishonored", "praised", "blamed", "forgiven", "punished", "rewarded", "penalized", "celebrated", "condemned",
        "accepted", "rejected", "welcomed", "banished", "embraced", "shunned", "included", "excluded", "invited", "uninvited",
        "chosen", "unchosen", "selected", "deselected", "elected", "appointed", "nominated", "promoted", "demoted", "hired",
        "fired", "employed", "unemployed", "retired", "working", "idle", "busy", "occupied", "vacant", "available",
        "unavailable", "accessible", "inaccessible", "open", "restricted", "public", "confidential", "classified", "declassified", "official",
        "unofficial", "formal", "informal", "casual", "ceremonial", "ritualistic", "sacred", "mundane", "profound", "superficial",
        "deep", "meaningful", "trivial", "significant", "consequential", "inconsequential", "pivotal", "marginal", "central", "peripheral",
        "primary", "secondary", "tertiary", "alpha", "omega", "beginning", "middle", "end", "prologue", "epilogue",
        "chapter", "verse", "stanza", "paragraph", "sentence", "word", "letter", "symbol", "sign", "signal",
        "code", "cipher", "message", "communication", "language", "dialect", "idiom", "expression", "phrase", "idiom",
        "proverb", "saying", "maxim", "aphorism", "quotation", "speech", "dialogue", "monologue", "narrative", "story",
        "tale", "fable", "myth", "legend", "epic", "saga", "chronicle", "history", "biography", "autobiography",
        "journal", "diary", "memoir", "novel", "novella", "short story", "play", "script", "screenplay", "poem",
        "lyric", "song", "ballad", "hymn", "anthem", "chant", "incantation", "spell", "curse", "blessing",
        "prophecy", "oracle", "riddle", "puzzle", "mystery", "enigma", "secret", "clue", "hint", "solution",
        "answer", "explanation", "interpretation", "analysis", "theory", "hypothesis", "experiment", "observation", "discovery", "invention",
        "creation", "masterpiece", "artifact", "relic", "monument", "ruin", "treasure", "gem", "jewel", "gold",
        "silver", "bronze", "iron", "steel", "stone", "wood", "glass", "crystal", "diamond", "pearl",
        "ruby", "emerald", "sapphire", "opal", "amber", "ivory", "bone", "shell", "feather", "fur",
        "skin", "leather", "silk", "cotton", "wool", "linen", "velvet", "lace", "embroidery", "tapestry",
        "sculpture", "painting", "drawing", "photograph", "film", "video", "animation", "music", "symphony", "opera",
        "ballet", "theater", "cinema", "literature", "poetry", "prose", "art", "craft", "skill", "talent",
        "genius", "prodigy", "master", "apprentice", "student", "teacher", "mentor", "guide", "leader", "follower",
        "hero", "villain", "protagonist", "antagonist", "character", "narrator", "author", "reader", "audience", "spectator",
        "critic", "reviewer", "scholar", "expert", "amateur", "novice", "beginner", "professional", "champion", "challenger",
        "winner", "loser", "victor", "vanquished", "survivor", "victim", "martyr", "saint", "sinner", "angel",
        "demon", "god", "goddess", "deity", "spirit", "ghost", "phantom", "apparition", "monster", "creature",
        "being", "entity", "alien", "extraterrestrial", "robot", "cyborg", "android", "machine", "computer", "program",
        "network", "internet", "web", "virtual", "reality", "simulation", "game", "toy", "doll", "puppet"
    ]
}
